[package]
name = "e-probe-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
eframe = "0.29.0"
egui = "0.29.0"
egui_file = "0.19.0"
goblin = "0.9.2"
probe-rs = {git = "https://github.com/probe-rs/probe-rs.git"}
